#!/bin/bash

IDIR=$1
ODIR=$2 
INDD=$3

IDIR=`echo $IDIR | sed 's:/*$::'`
ODIR=`echo $ODIR | sed 's:/*$::'`

ID=`echo $INDD | tail -c8`
H=`echo $ID | tail -c2`

SLCE=$IDIR'/'$ID'_reslice.nii.gz'
HEMI=$IDIR'/'$ID'_hemisphere_seg.nii.gz'
VENT=$IDIR'/'$ID'_ventricle_seg.nii.gz'
DOTS=$IDIR'/'$ID'_cortexdots_final.nii.gz'
PRNT=$ODIR'/tex/'$ID'_print_template_nocuts'
MOLD1=$ODIR'/'$ID'_hemi_mold.nii.gz'
MOLD2=$ODIR'/'$ID'_hemi_mold.stl'

brainmold -s $ID \
 	  -i $SLCE $HEMI \
 	  -o $ODIR \
	  -h $H \
	  -C \
 	  -d $DOTS

vtklevelset $MOLD1 $MOLD2 0.0

slab_postproc -d $ODIR -i $ID

pdflatex $PRNT'.tex'
